name: pr
on:
  push:
    branches: [master, feat/CK-1933]

jobs:
  tests:
    runs-on: docker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     pip install -r required
      #     pip install -r require.dev

      # - name: run tests
        # run: |
          # pytest --cov-report=xml --cov=status-update --cov-report term-missing --cov ${GITHUB_WORKSPACE}/src
          # sed -i "s|${GITHUB_WORKSPACE}|/github/workspace|g" coverage.xml

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            # coverage.xml
            action.yml
            sonar-project.properties
            src
          retention-days: 1

  sonarqube:
    needs: tests
    runs-on: docker

    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: files
          path: .

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
